package org.example.commonjpa.entity.enums;

public enum State {
    ACTIVE,
    PASSWORD,
    SEARCHING,
    WAITING_FOR_ITEM_NAME,
    WAITING_FOR_ITEM_NAME_EDIT,
    WAITING_FOR_ITEM_DESCRIPTION,
    WAITING_FOR_ITEM_DESCRIPTION_EDIT,
    WAITING_FOR_ITEM_PRICE,
    WAITING_FOR_ITEM_PRICE_EDIT,
    WAITING_FOR_ITEM_SIZES,
    WAITING_FOR_ITEM_SIZES_EDIT,
    WAITING_FOR_ITEM_QUANTITY,
    WAITING_FOR_ITEM_QUANTITY_EDIT,
    WAITING_FOR_ITEM_IMAGES,
    WAITING_FOR_ITEM_IMAGES_EDIT,
    WAITING_FOR_CATEGORY_NAME,
    WAITING_FOR_BRAND_NAME,
    WAITING_FOR_ITEM_NAME_SEARCH
}
